name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['15.0']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Build Package
      run: swift build -v
    
    - name: Run Tests
      run: swift test -v
    
    - name: Build Example
      run: |
        cd Examples/MiniMapExampleApp
        swift build -v
    
  test-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Swift
      run: |
        wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        wget -q https://swift.org/builds/swift-5.9-release/ubuntu2204/swift-5.9-RELEASE/swift-5.9-RELEASE-ubuntu22.04.tar.gz
        tar xzf swift-5.9-RELEASE-ubuntu22.04.tar.gz
        echo "$PWD/swift-5.9-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH
    
    - name: Build Package
      run: swift build -v
    
    - name: Run Tests
      run: swift test -v 