name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['15.0']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Build Package
      run: swift build -v
    
    - name: Run Tests
      run: swift test -v
    
    - name: Build Example
      run: |
        cd Examples/MiniMapExampleApp
        swift build -v
    
  # Note: Linux build removed because SpriteKit is not available on Linux
  # This package is designed for Apple platforms (iOS, macOS, tvOS, watchOS) 